// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFwaVE1lxjwYCNdEQN6z0cWwyapXnzpok',
    appId: '1:786244857392:web:8be5b5ab792526e51847f5',
    messagingSenderId: '786244857392',
    projectId: 'estacao-meteorologica-evet',
    authDomain: 'estacao-meteorologica-evet.firebaseapp.com',
    storageBucket: 'estacao-meteorologica-evet.appspot.com',
    measurementId: 'G-8X7TE6SB3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhGd2IUjxFYnTrPTQquew_F-apsroTW2Q',
    appId: '1:786244857392:android:76697c475a3c26571847f5',
    messagingSenderId: '786244857392',
    projectId: 'estacao-meteorologica-evet',
    storageBucket: 'estacao-meteorologica-evet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7s0a6W48buuFHFI1Z01t3sK_iuUQcROI',
    appId: '1:786244857392:ios:75dee07e0621febe1847f5',
    messagingSenderId: '786244857392',
    projectId: 'estacao-meteorologica-evet',
    storageBucket: 'estacao-meteorologica-evet.appspot.com',
    iosBundleId: 'com.estacaometeorologica.estacaoMeteorologica',
  );
}
